### ISSUE TITLE
Advanced Settings

### ISSUE THREAD

**Issue by losmicar** [WowzaMediaSystems/wse-rest-library-php#9]
1.) Is there any documentation/example how do you use AdvanceSettings class with advancedSettingsItem properties? I'am trying to update properties and I need to use my custom code:

`$wowzaApplication = new com\wowza\Application("livestream-19-201",  "LiveHTTPOrigin", "*", "*", "Moj app");

$advItem =new com\wowza\entities\application\helpers\AdvancedSettingItem();
$advItem->enabled = "true";
$advItem->restURI = null;
$advItem->canRemove = "true";
$advItem->name = "httpOriginMode";
$advItem->value = "on";
$advItem->defaultValue = "";
$advItem->type = "String";
$advItem->sectionName = "HTTPCacheOrigin";
$advItem->section = "/Root/Application/HTTPStreamer";
$advItem->documented ="true";
$wowzaApplication->updateProperty($advItem);
`

Where updateProperty is custom made f-tion:
`public function updateProperty($advancedSettings){
		//$this->_skip["name"]=1;
		//$this->_additional["version"]="1430601267443";
		$this->restURI = $this->restURI."/adv";
		if(is_array($advancedSettings)){
			$this->_additional["advancedSettings"]=$advancedSettings;
		}
		else
			$this->_additional["advancedSettings"]=array($advancedSettings);
			
		$entities = $this->getEntites(func_get_args(), null);
		return $this->sendRequest($this->preparePropertiesForRequest(),array(), self::VERB_PUT);
	}`

Also "preparePropertiesForRequest" need to be modified:

`private function preparePropertiesForRequest(){
		$classPropNames = get_class_vars(get_class($this));
		$props = new \stdClass();
		foreach($classPropNames as $key=>$val){
			if(isset($this->$key)){
				if(preg_match("/^(\_)/", $key)){
					continue;
				}
				if(isset($this->_skip[$key])){
					continue;
				}
				$props->$key = $this->$key;
			}
		}
		//Added by losmi
		if(count($this->_additional)>0){
			foreach($this->_additional as $key=>$val){
				$props->$key=$val;
			}
		}
		return $props;
	}`

It looks like this API is incomplete and need a lot modification and documentation.

2.) TranscoderConfig class is not working when used with php 7. All class properties that are type of array are returning:

_"Can not deserialize instance of java.lang.Boolean out of START_ARRAY token\n at [Source: java.io.ByteArrayInputStream@74e63af9; line: 1, column: 2143] (through reference chain: com.wowza.wms.rest.vhosts.applications.ApplicationConfig[\"transcoderConfig\"]->com.wowza.wms.rest.vhosts.applications.transcoder.TranscoderAppConfig[\"available\"])_

Also the main **problem is "template" property** that need to be type of Object and can't be type of array. When changed to Object, and above properties to proper int/bool types, class is working properly, except there is no explanation or any documentation how to setup Transcoding Templates. I've tried to create array in object (e.g $this->templates->templates[] = new TemplateItem(); with "id" and "href" property but it doesn't work).

**Comment by myoung1620** [comment]
This example set is just a starter set to build off of for the time being.  I've committed a small modification to demonstrate a simple way to leverage the advanced settings.  

Thanks!

**Comment by losmicar** [comment]
Since you last update class wowza line 74, you've left there: var_dump($entities); inside the sendRequest method.

Thanks for the update. Still many other issues remains.

**Comment by losmicar** [comment]
For those who will use advancedSettings, keep in mind that calling new method will remove all modules from your app settings. Until this is fixed there is a walk-around to either update your app again with new modules list or use this fix from wowza forum (provided by Michelle): https://www.wowza.com/community/questions/43509/hot-to-create-app-type-of-livehttporigin-via-rest.html

**Comment by myoung1620** [comment]
We've extended the example set to demonstrate how to update both the properties and modules alike.  Please see the latest.

**Comment by losmicar** [comment]
Work like a charm. Thanks for the updates.
